site_name: ES6学习笔记
nav:
  - '目录': index.md
  - 'ECMAScript 6简介': 'intro.md'
  - 'let 和 const 命令': 'let.md'
  - '变量的解构赋值': 'destructuring.md'
  - '字符串的扩展': 'string.md'
  - '字符串的新增方法': 'string-methods.md'
  - '正则的扩展': 'regex.md'
  - '数值的扩展': 'number.md'
  - '函数的扩展': 'function.md'
  - '数组的扩展': 'array.md'
  - '对象的扩展': 'object.md'
  - '对象的新增方法': 'object-methods.md'
  - 'Symbol': 'symbol.md'
  - 'Set 和 Map 数据结构': 'set-map.md'
  - 'Proxy': 'proxy.md'
  - 'Reflect': 'reflect.md'
  - 'Promise 对象': 'promise.md'
  - 'Iterator 和 for...of 循环': 'iterator.md'
  - 'Generator 函数的语法': 'generator.md'
  - 'Generator 函数的异步应用': 'generator-async.md'
  - 'async 函数': 'async.md'
  - 'Class 的基本语法': 'class.md'
  - 'Class 的继承': 'class-extends.md'
  - 'Module 的语法': 'module.md'
  - 'Module 的加载实现': 'module-loader.md'
  - '编程风格': 'style.md'
  - '读懂规格': 'spec.md'
  - '异步遍历器': 'async-iterator.md'
  - 'ArrayBuffer': 'arraybuffer.md'
  - '最新提案': 'proposals.md'
  - 'Decorator': 'decorator.md'
  - '参考链接': 'reference.md'
theme: readthedocs
plugins:
  - search